name: MuleSoft CI/CD

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build Mule Application
        run: mvn clean package -DskipMunitTests

      - name: Deploy to CloudHub 2.0
        run: |
          mvn deploy \
          -DmuleDeploy \
          -Danypoint.username=${{ secrets.ANYPOINT_USERNAME }} \
          -Danypoint.password=${{ secrets.ANYPOINT_PASSWORD }}
